"""empty message

Revision ID: 338ec3ff8b4d
Revises: None
Create Date: 2014-04-25 13:27:43.901364

"""

# revision identifiers, used by Alembic.
revision = '338ec3ff8b4d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('highschool', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('currentcity', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('facebook_pages',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('num_likes', sa.BigInteger(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('twitter_users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name')
    )
    op.create_table('twitter_tweets',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['twitter_users.screen_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_pages_users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['facebook_pages.page_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['facebook_users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'page_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_pages_users')
    op.drop_table('twitter_tweets')
    op.drop_table('twitter_users')
    op.drop_table('facebook_pages')
    op.drop_table('facebook_users')
    ### end Alembic commands ###
