"""Create boe_contributors and boe_democratic_committees tables.

Revision ID: 254affa19b81
Revises: 4d90654cb043
Create Date: 2014-05-10 18:05:53.054786

"""

# revision identifiers, used by Alembic.
revision = '254affa19b81'
down_revision = '26d94a184169'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boe_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributed_by', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_address', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('contributor_address', sa.String(), nullable=True),
    sa.Column('contrib_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boe_democratic_committees',
    sa.Column('committee_name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boe_democratic_committees')
    op.drop_table('boe_contributors')
    ### end Alembic commands ###
