"""Add zipcode to boe_contributors.

Revision ID: 259bedf52cb2
Revises: 348a19576ac8
Create Date: 2014-05-10 18:21:33.934077

"""

# revision identifiers, used by Alembic.
revision = '259bedf52cb2'
down_revision = '254affa19b81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boe_contributors', sa.Column('zipcode', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boe_contributors', 'zipcode')
    ### end Alembic commands ###
