"""empty message

Revision ID: 54da8d9c724f
Revises: 41c833dfc70d
Create Date: 2014-05-11 15:53:23.288326

"""

# revision identifiers, used by Alembic.
revision = '54da8d9c724f'
down_revision = '348a19576ac8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'type', 'uid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    ### end Alembic commands ###
