"""Create facebook_statuses, facebook_locations, facebook_families, facebook_friends.

Revision ID: 1b1bb7abdd3a
Revises: 54da8d9c724f
Create Date: 2014-05-19 13:26:50.458514

"""

# revision identifiers, used by Alembic.
revision = '1b1bb7abdd3a'
down_revision = '54da8d9c724f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_statuses',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('facebook_locations',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('loc_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('gid', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('loc_id')
    )
    op.create_table('facebook_families',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['facebook_users.uid'], ),
    sa.ForeignKeyConstraint(['uid'], ['facebook_users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'profile_id')
    )
    op.create_table('facebook_friends',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid2', sa.BigInteger(), nullable=False),
    sa.Column('uid1', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['uid1'], ['facebook_users.uid'], ),
    sa.ForeignKeyConstraint(['uid2'], ['facebook_users.uid'], ),
    sa.PrimaryKeyConstraint('uid2', 'uid1')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_friends')
    op.drop_table('facebook_families')
    op.drop_table('facebook_locations')
    op.drop_table('facebook_statuses')
    ### end Alembic commands ###
