"""empty message

Revision ID: 4cbdf7a28c0c
Revises: 6223d04dade
Create Date: 2014-05-23 08:30:16.843358

"""

# revision identifiers, used by Alembic.
revision = '4cbdf7a28c0c'
down_revision = '6223d04dade'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_users', sa.Column('contact_time', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook_users', 'contact_time')
    ### end Alembic commands ###
