"""empty message

Revision ID: 3a8a93b5f622
Revises: 11f4959c79e8
Create Date: 2014-06-08 19:11:25.554987

"""

# revision identifiers, used by Alembic.
revision = '3a8a93b5f622'
down_revision = '11f4959c79e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_users', sa.Column('nu', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook_users', 'nu')
    ### end Alembic commands ###
