"""empty message

Revision ID: 11f4959c79e8
Revises: c2186e9dbdd
Create Date: 2014-05-28 17:30:25.578120

"""

# revision identifiers, used by Alembic.
revision = '11f4959c79e8'
down_revision = 'c2186e9dbdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_users', sa.Column('scrape_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook_users', 'scrape_status')
    ### end Alembic commands ###
