"""empty message

Revision ID: 1a8190e51405
Revises: 259bedf52cb2
Create Date: 2014-05-11 15:32:18.913516

"""

# revision identifiers, used by Alembic.
revision = '1a8190e51405'
down_revision = '259bedf52cb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'uid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    ### end Alembic commands ###
