"""empty message

Revision ID: 23e20e98fe65
Revises: 2e676f7aa44f
Create Date: 2014-04-23 17:03:08.129498

"""

# revision identifiers, used by Alembic.
revision = '23e20e98fe65'
down_revision = '2e676f7aa44f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('facebook_username', sa.String(), nullable=True))
    op.add_column('contributors', sa.Column('linkedin_username', sa.String(), nullable=True))
    op.add_column('contributors', sa.Column('twitter_username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'contributors', ['twitter_username'])
    op.create_unique_constraint(None, 'contributors', ['facebook_username'])
    op.create_unique_constraint(None, 'contributors', ['linkedin_username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributors')
    op.drop_constraint(None, 'contributors')
    op.drop_constraint(None, 'contributors')
    op.drop_column('contributors', 'twitter_username')
    op.drop_column('contributors', 'linkedin_username')
    op.drop_column('contributors', 'facebook_username')
    ### end Alembic commands ###
