"""empty message

Revision ID: 2abaf2aa7bb9
Revises: None
Create Date: 2014-04-24 18:30:05.557702

"""

# revision identifiers, used by Alembic.
revision = '2abaf2aa7bb9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('highschool', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('currentcity', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('twitter_users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name')
    )
    op.create_table('facebook_locations',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('loc_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('gid', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('loc_id')
    )
    op.create_table('facebook_pages',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('num_likes', sa.BigInteger(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('facebook_statuses',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('twitter_tweets',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['twitter_users.screen_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_pages_users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['facebook_pages.page_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['facebook_users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'page_id')
    )
    op.create_table('facebook_families',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['facebook_users.uid'], ),
    sa.ForeignKeyConstraint(['uid'], ['facebook_users.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'profile_id')
    )
    op.create_table('facebook_friends',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uid2', sa.BigInteger(), nullable=False),
    sa.Column('uid1', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['uid1'], ['facebook_users.uid'], ),
    sa.ForeignKeyConstraint(['uid2'], ['facebook_users.uid'], ),
    sa.PrimaryKeyConstraint('uid2', 'uid1')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_friends')
    op.drop_table('facebook_families')
    op.drop_table('facebook_pages_users')
    op.drop_table('twitter_tweets')
    op.drop_table('facebook_statuses')
    op.drop_table('facebook_pages')
    op.drop_table('facebook_locations')
    op.drop_table('twitter_users')
    op.drop_table('facebook_users')
    ### end Alembic commands ###
