"""empty message

Revision ID: 348a19576ac8
Revises: 254affa19b81
Create Date: 2014-05-10 18:14:03.648810

"""

# revision identifiers, used by Alembic.
revision = '348a19576ac8'
down_revision = '254affa19b81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boe_contributors', sa.Column('contributor_addr_lat', sa.Float(), nullable=True))
    op.add_column('boe_contributors', sa.Column('contributor_addr_lng', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boe_contributors', 'contributor_addr_lng')
    op.drop_column('boe_contributors', 'contributor_addr_lat')
    ### end Alembic commands ###
