"""empty message

Revision ID: 39142e933bbb
Revises: 26d94a184169
Create Date: 2014-05-10 18:00:08.883034

"""

# revision identifiers, used by Alembic.
revision = '39142e933bbb'
down_revision = '26d94a184169'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
