"""empty message

Revision ID: 41c833dfc70d
Revises: 1a8190e51405
Create Date: 2014-05-11 15:51:11.978776

"""

# revision identifiers, used by Alembic.
revision = '41c833dfc70d'
down_revision = '1a8190e51405'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('type', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'type')
    ### end Alembic commands ###
