"""empty message

Revision ID: 43f738115918
Revises: 4fb51e2ca8ca
Create Date: 2014-04-29 13:04:11.584552

"""

# revision identifiers, used by Alembic.
revision = '43f738115918'
down_revision = '4fb51e2ca8ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
