"""empty message

Revision ID: 4d90654cb043
Revises: 39142e933bbb
Create Date: 2014-05-10 18:00:36.963841

"""

# revision identifiers, used by Alembic.
revision = '4d90654cb043'
down_revision = '39142e933bbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
