"""empty message

Revision ID: 6223d04dade
Revises: 54da8d9c724f
Create Date: 2014-05-17 17:45:07.686566

"""

# revision identifiers, used by Alembic.
revision = '6223d04dade'
down_revision = '1b1bb7abdd3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_users', sa.Column('donor', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook_users', 'donor')
    ### end Alembic commands ###
